### PR TITLE
Adds final state draw.io skeleton architecture diagram

### PR DESCRIPTION
**Pull request by carjug**
### What does this change?
Adds png for our desired final state architecture diagram to our documentation

### What does this change look like?
Diagram

### GitHub cards
Completes part of #27

### CODE REVIEW

**Comment by carjug** [comment]
Question for the group: do we also need to add an ADR for the architecture we've come up with? That feels like it'd be covered by the tech stack ADR mostly, but....I wasn't quite sure.

**Review by amymok — COMMENTED** [review]
Looks good!  I would suggest to rename the file to something like `final_state_architecture_diagram.png`, `architecture_diagram.png`, etc. because as-is reads like `state_diagram`, and it may be confusing that this is an actual "state diagram" and not an architecture diagram.

**Comment by amymok** [comment]
> Question for the group: do we also need to add an ADR for the architecture we've come up with? That feels like it'd be covered by the tech stack ADR mostly, but....I wasn't quite sure.
> CC: @amymok @alexsoble

I think we need to explain and record some of the choices as ADRs if we haven't yet.  For example, CircleCI, S3.

**Comment by carjug** [comment]
> Looks good! I would suggest to rename the file to something like `final_state_architecture_diagram.png`, `architecture_diagram.png`, etc. because as-is reads like `state_diagram`, and it may be confusing that this is an actual "state diagram" and not an architecture diagram.

Got it! Fixed

**Comment by alexsoble** [comment]
Looks good to me as a starting point! A good visual we can use to talk with our PM and PO! 

I approve this PR, but I think we'll also want PM and maybe PO review for this one.

**Review by alexsoble — APPROVED** [review]

**Comment by alexsoble** [comment]
I can also easily import the PNG into draw.io and edit it, which is great!

**Review by amymok — APPROVED** [review]
Looks great!

**Comment by carjug** [comment]
@amymok to respond to your second comment, I think the CircleCI choice is covered by [#55](https://github.com/18F/OPRE-Unicorn/issues/55). The choice for S3 is not covered anywhere but I'm not sure if we should add it as a part of this issue or create a new one? either is fine for me.

**Comment by amymok** [comment]
Oh I do not mean adding to this issue, I am just saying we should probably have an ADR on those.

**Comment by ninamak** [comment]
Would it work to walk me through this diagram during our Demo block on Mon (7/12)?

Who is going to create cards for the ADRs that need to be written up?

**Comment by carjug** [comment]
@ninamak Sure, I can walk you through it. 
There is one card that needs to be made for one ADR, I can do that.

**Pull request merged**
