### PR TITLE
Add ADR for Document Storage

### PR DESCRIPTION
**Pull request by amymok**
## What does this change? 

+ Adds ADR for document storage

## What does this change look like?

[Preview link for folder.](https://github.com/18F/OPRE-MAPS/tree/aym/68/storage/docs/adr/007-use-s3-for-document-storage.md) 👁️ 

## GitHub cards

Completes #68.

### CODE REVIEW

**Review by alexsoble — APPROVED** [review]
LGTM!

**Review by ninamak — APPROVED** [review]
LGTM!

**Review by carjug — APPROVED** [review]
LGTM :shipit:

**Comment by carjug** [comment]
Merging.

**Comment by carjug** [comment]
Whoops I merged before we changed to "Accepted", can you add that change @amymok otherwise I can :)

**Comment by carjug** [comment]
I didn't delete the branch so the same branch should be fine.

**Comment by amymok** [comment]
I am not sure if I can still push it properly 🤔 .  There are a few ADRs that actually still in Proposed state.  I will start another PR instead to change all of them at once.  I will delete this branch for now.

**Pull request merged**
