### PR TITLE
Add GH issue template to standardize the info we include on cards

### PR DESCRIPTION
**Pull request by ninamak**
Expected that we may create different templates for feature work, bugs, etc.

### CODE REVIEW

**Comment by carjug** [comment]
Hey @ninamak if you want to assign people to review your PR, there is a heading labeled "Reviewers" on the right hand column that allows you to do so. This will send whoever you assign an email to let them know they've been assigned.

**Comment by carjug** [comment]
LGTM 🚢

**Review by carjug — APPROVED** [review]
LGTM :shipit:

**Review by alexsoble — APPROVED** [review]

**Review by amymok — APPROVED** [review]
Looks great to me!

**Pull request merged**
