### PR TITLE
Use active voice for ADR filenames

### PR DESCRIPTION
**Pull request by alexsoble**
## Notes 

+ As per recommendation: https://18f.gsa.gov/2021/07/06/architecture_decision_records_helpful_now_invaluable_later/

> A newcomer should be able to skim the file names of your ADRs and get a concise, high-level overview of the life of your product. Have a consistent naming convention for your ADR files that briefly and accurately describes the decision. For example, a file name like use-postgresql-for-database.md that’s written in an active voice is more readable than database-selection.md.

## Preview link

https://github.com/18F/OPRE-Unicorn/tree/ars/25/use-active-voice-for-adrs/docs/adr

### CODE REVIEW

**Comment by alexsoble** [comment]
Oops! Tagged folks as assignees instead of reviewers, my mistake!

**Review by carjug — APPROVED** [review]
LGTM :shipit:

**Comment by alexsoble** [comment]
@amymok, if you approve, could you also merge on approving? Thanks!

**Review by amymok — APPROVED** [review]
LGTM!!

**Pull request merged**
