### PR TITLE
Adopt Architecture Decision Records; add ADRs for cloud environment and version control

### LINKED ISSUE #24: Decide on preferred application environment
Decide on which cloud environment (cloud.gov, HHS AWS, ACF AWS) and document why.

Explain any differences between v0.1 v1.0 decisions

**Tasks**

- [ ] Document decision and reasons why

### LINKED ISSUE #26: Decide on tech services needed for version control
As a team, we need to agree upon which technologies we will be using for version control.

Table for reference:

  | Carly | Amy | Alex
-- | -- | -- | --
Technology for version control | GitHub | GitHub | GitHub

**Tasks**

- [ ] Determine technology for version control and document with a lightweight decision record
- [ ] Create "procurement" and/or any implementation follow on tasks for version control

### PR DESCRIPTION
**Pull request by alexsoble**
## What does this change? 

+ Adds an initial Architecture Decision Record
+ Adds ADR for cloud environment 
+ Adds ADR for version control

ADRs co-written with @amymok and @carjug!

## What does this change look like?

[Preview link for folder.](https://github.com/18F/OPRE-MAPS/tree/ars/23/create-structure-for-adrs/docs/adr) 👁️ 

## GitHub cards

Resolves #24.
Resolves #26.

Merging this PR should [automatically close the associated cards](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### CODE REVIEW

**Comment by alexsoble** [comment]
@amymok @carjug Here's a structure we can use to record our work during this afternoon's "Document tech decisions!" jam.

**Review by amymok — APPROVED** [review]
Looks great! 🎉

**Review by ninamak — APPROVED** [review]
All looks great to me!

**Review by carjug — APPROVED** [review]
LGTM :shipit:

**Comment by carjug** [comment]
Merged! @alexsoble

**Pull request merged**
